language: cpp
compiler:
  - clang
notifications:
  email:
    - zach.allaun+travis@gmail.com
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init()'
  - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("FactCheck"))`)'
  - julia -e 'Pkg.pin("FactCheck"); Pkg.resolve()'
  - julia ~/.julia/v0.3/FactCheck/test/test_factcheck.jl
